name       : libdovi
version    : 3.1.2
release    : 1
source     :
    - https://github.com/quietvoid/dovi_tool/archive/refs/tags/libdovi-3.1.2.tar.gz : 3c74f8f6afdb7d4be97210df201a28a48676b2ebe10c20961176e81e2fd98c36
license    : MIT
component  : multimedia.library
summary    : Library to read & write Dolby Vision metadata
description: |
    Library to read & write Dolby Vision metadata.
builddeps  :
    - cargo-c
networking : yes
build      : |
    pushd dolby_vision
    cargo cbuild \
        --library-type=cdylib \
        --prefix=/usr \
        --release
install    : |
    pushd dolby_vision
    cargo cinstall \
        --destdir=$installdir \
        --libdir=%libdir% \
        --library-type=cdylib \
        --prefix=/usr
